
package Vista;

import Controlador.DocenteControlador;
import Controlador.HerramientaControlador;
import Controlador.MaterialControlador;
import Controlador.RetiroHerramControlador;
import Controlador.RetiroMaterialControlador;
import Modelo.Docente;
import Modelo.Herramienta;
import Modelo.Material;
import Modelo.RetiroHerramienta;
import Modelo.RetiroMaterial;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan Medina
 */
public class vistaPrincipal extends javax.swing.JFrame {

    
    public vistaPrincipal() {
       initComponents();
       setLocationRelativeTo(null);
       
       jTabbedPane1.setBackgroundAt(0, (new Color(132, 182, 244)));
       jTabbedPane1.setBackgroundAt(1, (new Color(253, 253, 150)));
       jTabbedPane1.setBackgroundAt(2, (new Color(119, 221, 119)));
       jTabbedPane1.setBackgroundAt(3, (new Color(255, 105, 97)));
       jTabbedPane1.setBackgroundAt(4, (new Color(253, 202, 225)));
       DocenteControlador.obtenerIdDocentes();
       HerramientaControlador.obtenerIdHerramienta();
       MaterialControlador.obtenerIdMaterial();
       
       ImageIcon img = new ImageIcon("src/main/resources/logoET17.png");       
       setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        RetiroHerramienta = new javax.swing.JPanel();
        btnBuscarRetiroHerramientas = new javax.swing.JButton();
        btnAgregarRetiroHerramienta = new javax.swing.JButton();
        btnDevolucionHerramienta = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtResponsable = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFechaRetiroHerramienta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIDApellidoDocente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnListadoRetiroHerramientas = new javax.swing.JButton();
        btnCargarDocente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIDNombreDocente = new javax.swing.JTextField();
        cBIDHerramienta = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtIDNombreHerramienta = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtIDMarcaHerramienta = new javax.swing.JTextField();
        btnCargarHerramienta = new javax.swing.JButton();
        cBIDDocenteH = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        spinnerStockRH = new javax.swing.JSpinner();
        RetiroMaterial = new javax.swing.JPanel();
        btnAgregarRetiroMaterial = new javax.swing.JButton();
        btnBuscarRetiroMaterial = new javax.swing.JButton();
        btnListadoRetiroMaterial = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtResponsable2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFechaRetiroMaterial = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtIDApellidoDocenteM = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtIDNombreDocenteM = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtIDMateriaPrima = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtIDTipoMaterial = new javax.swing.JTextField();
        btnCargarDocente1 = new javax.swing.JButton();
        btnCargarMaterial = new javax.swing.JButton();
        cBIDDocenteM = new javax.swing.JComboBox<>();
        cBIDMaterial = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        txtIDMedidaMaterial = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        spinnerStockRM = new javax.swing.JSpinner();
        Docentes = new javax.swing.JPanel();
        btnAgregarDocente = new javax.swing.JButton();
        btnBuscarDocente = new javax.swing.JButton();
        btnEditarDocente = new javax.swing.JButton();
        btnEliminarDocente = new javax.swing.JButton();
        btnListadoDocente = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cBCargoDocente = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnNuevoCargo = new javax.swing.JButton();
        Herramientas = new javax.swing.JPanel();
        btnAgregarHerramienta = new javax.swing.JButton();
        btnBuscarHerramienta = new javax.swing.JButton();
        btnListadoHerramienta = new javax.swing.JButton();
        btnEliminarHerramienta = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtNombreHerramienta = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtMarcaHerramienta = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        btnAgregarStockH = new javax.swing.JButton();
        spinnerStockHerramienta = new javax.swing.JSpinner();
        Materiales = new javax.swing.JPanel();
        btnAgregarMaterial = new javax.swing.JButton();
        btnBuscarMaterial = new javax.swing.JButton();
        btnListadoMaterial = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cBMateriaPrima = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        txtTipoMaterial = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtMedida = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnAgregarStockM = new javax.swing.JButton();
        spinnerStockMaterial = new javax.swing.JSpinner();
        btnNuevaMatPrima = new javax.swing.JButton();
        btnEliminarMaterial = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Depósito Taller ");
        setBackground(new java.awt.Color(102, 102, 102));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(getLocation());
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(775, 550));
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(730, 460));

        RetiroHerramienta.setBackground(new java.awt.Color(132, 182, 244));
        RetiroHerramienta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        btnBuscarRetiroHerramientas.setText("Buscar");
        btnBuscarRetiroHerramientas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRetiroHerramientasActionPerformed(evt);
            }
        });

        btnAgregarRetiroHerramienta.setText("Confirmar");
        btnAgregarRetiroHerramienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRetiroHerramientaActionPerformed(evt);
            }
        });

        btnDevolucionHerramienta.setText("Devolución de Herramienta");
        btnDevolucionHerramienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucionHerramientaActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("CREAR NUEVO RETIRO DE HERRAMIENTA");

        jLabel1.setText("Responsable del Depósito:");

        txtResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResponsableActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha de Retiro");

        txtFechaRetiroHerramienta.setEditable(false);
        txtFechaRetiroHerramienta.setText(FechaParaM());
        txtFechaRetiroHerramienta.setName(""); // NOI18N
        txtFechaRetiroHerramienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaRetiroHerramientaActionPerformed(evt);
            }
        });

        jLabel2.setText("ID del Docente");

        txtIDApellidoDocente.setEditable(false);
        txtIDApellidoDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDApellidoDocenteActionPerformed(evt);
            }
        });

        jLabel3.setText("ID de Herramienta");

        btnListadoRetiroHerramientas.setText("Ver Listado");
        btnListadoRetiroHerramientas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoRetiroHerramientasActionPerformed(evt);
            }
        });

        btnCargarDocente.setText("Cargar Docente");
        btnCargarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarDocenteActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre:");

        jLabel6.setText("Apellido:");

        txtIDNombreDocente.setEditable(false);

        cBIDHerramienta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----" }));

        jLabel11.setText("Nombre:");

        txtIDNombreHerramienta.setEditable(false);
        txtIDNombreHerramienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDNombreHerramientaActionPerformed(evt);
            }
        });

        jLabel20.setText("Marca:");

        txtIDMarcaHerramienta.setEditable(false);

        btnCargarHerramienta.setText("Cargar Herramienta");
        btnCargarHerramienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarHerramientaActionPerformed(evt);
            }
        });

        cBIDDocenteH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----" }));

        jLabel34.setText("Stock a Retirar:");

        javax.swing.GroupLayout RetiroHerramientaLayout = new javax.swing.GroupLayout(RetiroHerramienta);
        RetiroHerramienta.setLayout(RetiroHerramientaLayout);
        RetiroHerramientaLayout.setHorizontalGroup(
            RetiroHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RetiroHerramientaLayout.createSequentialGroup()
                .addGroup(RetiroHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RetiroHerramientaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(RetiroHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RetiroHerramientaLayout.createSequentialGroup()
                                .addGroup(RetiroHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(RetiroHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RetiroHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtResponsable)
                                        .addComponent(txtFechaRetiroHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(RetiroHerramientaLayout.createSequentialGroup()
                                        .addComponent(cBIDDocenteH, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCargarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RetiroHerramientaLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIDApellidoDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIDNombreDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RetiroHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(RetiroHerramientaLayout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cBIDHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCargarHerramienta))
                                .addGroup(RetiroHerramientaLayout.createSequentialGroup()
                                    .addGroup(RetiroHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RetiroHerramientaLayout.createSequentialGroup()
                                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(spinnerStockRH, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(RetiroHerramientaLayout.createSequentialGroup()
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtIDNombreHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(55, 55, 55)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtIDMarcaHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 264, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RetiroHerramientaLayout.createSequentialGroup()
                        .addContainerGap(351, Short.MAX_VALUE)
                        .addComponent(btnBuscarRetiroHerramientas)
                        .addGap(18, 18, 18)
                        .addComponent(btnDevolucionHerramienta)
                        .addGap(18, 18, 18)
                        .addComponent(btnListadoRetiroHerramientas)))
                .addContainerGap())
            .addGroup(RetiroHerramientaLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(btnAgregarRetiroHerramienta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RetiroHerramientaLayout.setVerticalGroup(
            RetiroHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RetiroHerramientaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(RetiroHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RetiroHerramientaLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addGroup(RetiroHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cBIDDocenteH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCargarDocente)))
                    .addGroup(RetiroHerramientaLayout.createSequentialGroup()
                        .addComponent(txtResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaRetiroHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RetiroHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDNombreDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDApellidoDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RetiroHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnCargarHerramienta)
                    .addComponent(cBIDHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RetiroHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDMarcaHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDNombreHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RetiroHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(spinnerStockRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnAgregarRetiroHerramienta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addGroup(RetiroHerramientaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListadoRetiroHerramientas)
                    .addComponent(btnDevolucionHerramienta)
                    .addComponent(btnBuscarRetiroHerramientas))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Retiro Herramientas", RetiroHerramienta);

        RetiroMaterial.setBackground(new java.awt.Color(253, 253, 150));

        btnAgregarRetiroMaterial.setText("Confirmar");
        btnAgregarRetiroMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRetiroMaterialActionPerformed(evt);
            }
        });

        btnBuscarRetiroMaterial.setText("Buscar");
        btnBuscarRetiroMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRetiroMaterialActionPerformed(evt);
            }
        });

        btnListadoRetiroMaterial.setText("Ver Listado");
        btnListadoRetiroMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoRetiroMaterialActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("CREAR NUEVO RETIRO DE MATERIALES");

        jLabel7.setText("Responsable del Depósito:");

        txtResponsable2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResponsable2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Fecha de Retiro");

        txtFechaRetiroMaterial.setEditable(false);
        txtFechaRetiroMaterial.setText(FechaParaM());
        txtFechaRetiroMaterial.setName(""); // NOI18N
        txtFechaRetiroMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaRetiroMaterialActionPerformed(evt);
            }
        });

        jLabel9.setText("ID del Docente");

        jLabel10.setText("ID del Material");

        jLabel22.setText("Apellido:");

        txtIDApellidoDocenteM.setEditable(false);
        txtIDApellidoDocenteM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDApellidoDocenteMActionPerformed(evt);
            }
        });

        jLabel26.setText("Nombre:");

        txtIDNombreDocenteM.setEditable(false);

        jLabel30.setText("Materia Prima:");

        txtIDMateriaPrima.setEditable(false);
        txtIDMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDMateriaPrimaActionPerformed(evt);
            }
        });

        jLabel32.setText("Tipo:");

        txtIDTipoMaterial.setEditable(false);

        btnCargarDocente1.setText("Cargar Docente");
        btnCargarDocente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarDocente1ActionPerformed(evt);
            }
        });

        btnCargarMaterial.setText("Cargar Material");
        btnCargarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarMaterialActionPerformed(evt);
            }
        });

        cBIDDocenteM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----" }));

        cBIDMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----" }));

        jLabel33.setText("Medida:");

        txtIDMedidaMaterial.setEditable(false);

        jLabel35.setText("Stock a Retirar: ");

        javax.swing.GroupLayout RetiroMaterialLayout = new javax.swing.GroupLayout(RetiroMaterial);
        RetiroMaterial.setLayout(RetiroMaterialLayout);
        RetiroMaterialLayout.setHorizontalGroup(
            RetiroMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RetiroMaterialLayout.createSequentialGroup()
                .addGroup(RetiroMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RetiroMaterialLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(RetiroMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RetiroMaterialLayout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIDApellidoDocenteM, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIDNombreDocenteM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RetiroMaterialLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cBIDMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCargarMaterial))
                            .addGroup(RetiroMaterialLayout.createSequentialGroup()
                                .addGroup(RetiroMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RetiroMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(RetiroMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(RetiroMaterialLayout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtFechaRetiroMaterial))
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(RetiroMaterialLayout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtResponsable2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(RetiroMaterialLayout.createSequentialGroup()
                                        .addGap(161, 161, 161)
                                        .addComponent(cBIDDocenteM, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnCargarDocente1))
                            .addGroup(RetiroMaterialLayout.createSequentialGroup()
                                .addGroup(RetiroMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(RetiroMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIDMateriaPrima, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(spinnerStockRM))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIDTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIDMedidaMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RetiroMaterialLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBuscarRetiroMaterial)
                        .addGap(18, 18, 18)))
                .addComponent(btnListadoRetiroMaterial)
                .addContainerGap())
            .addGroup(RetiroMaterialLayout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(btnAgregarRetiroMaterial)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RetiroMaterialLayout.setVerticalGroup(
            RetiroMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RetiroMaterialLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(RetiroMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResponsable2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RetiroMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtFechaRetiroMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(RetiroMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargarDocente1)
                    .addComponent(cBIDDocenteM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(RetiroMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDNombreDocenteM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDApellidoDocenteM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RetiroMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(btnCargarMaterial)
                    .addComponent(cBIDMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RetiroMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDMedidaMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RetiroMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(spinnerStockRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(btnAgregarRetiroMaterial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addGroup(RetiroMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListadoRetiroMaterial)
                    .addComponent(btnBuscarRetiroMaterial))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Retiro Materiales", RetiroMaterial);

        Docentes.setBackground(new java.awt.Color(119, 221, 119));

        btnAgregarDocente.setText("Confirmar");
        btnAgregarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDocenteActionPerformed(evt);
            }
        });

        btnBuscarDocente.setText("Buscar");
        btnBuscarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDocenteActionPerformed(evt);
            }
        });

        btnEditarDocente.setText("Editar");
        btnEditarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDocenteActionPerformed(evt);
            }
        });

        btnEliminarDocente.setText("Eliminar");
        btnEliminarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDocenteActionPerformed(evt);
            }
        });

        btnListadoDocente.setText("Ver Listado");
        btnListadoDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoDocenteActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("AGREGAR NUEVO DOCENTE");

        jLabel12.setText("Apellido:");

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });

        jLabel15.setText("Nombre");

        txtNombre.setName(""); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel14.setText("Cargo");

        cBCargoDocente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MEP", "Jefe de Sección ", "Jefe Gral de Taller", "Profesor/a/x" }));
        cBCargoDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBCargoDocenteActionPerformed(evt);
            }
        });

        jLabel13.setText("Telefóno");

        btnNuevoCargo.setText("Crear Nuevo Cargo");
        btnNuevoCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoCargoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DocentesLayout = new javax.swing.GroupLayout(Docentes);
        Docentes.setLayout(DocentesLayout);
        DocentesLayout.setHorizontalGroup(
            DocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocentesLayout.createSequentialGroup()
                .addGroup(DocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DocentesLayout.createSequentialGroup()
                        .addGap(0, 364, Short.MAX_VALUE)
                        .addComponent(btnBuscarDocente)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarDocente)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarDocente)
                        .addGap(18, 18, 18)
                        .addComponent(btnListadoDocente))
                    .addGroup(DocentesLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(DocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DocentesLayout.createSequentialGroup()
                                .addGroup(DocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(DocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtApellido)
                                    .addComponent(txtNombre)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(cBCargoDocente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(btnNuevoCargo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(DocentesLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(btnAgregarDocente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DocentesLayout.setVerticalGroup(
            DocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DocentesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(DocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(DocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBCargoDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoCargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregarDocente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addGroup(DocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListadoDocente)
                    .addComponent(btnEliminarDocente)
                    .addComponent(btnEditarDocente)
                    .addComponent(btnBuscarDocente))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Docentes", Docentes);

        Herramientas.setBackground(new java.awt.Color(255, 105, 97));

        btnAgregarHerramienta.setText("Confirmar");
        btnAgregarHerramienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarHerramientaActionPerformed(evt);
            }
        });

        btnBuscarHerramienta.setText("Buscar");
        btnBuscarHerramienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHerramientaActionPerformed(evt);
            }
        });

        btnListadoHerramienta.setText("Ver Listado");
        btnListadoHerramienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoHerramientaActionPerformed(evt);
            }
        });

        btnEliminarHerramienta.setText("Eliminar Herramienta");
        btnEliminarHerramienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarHerramientaActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("INGRESO NUEVA HERRAMIENTA");

        jLabel27.setText("Nombre");

        txtNombreHerramienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreHerramientaActionPerformed(evt);
            }
        });

        jLabel28.setText("Marca");

        txtMarcaHerramienta.setName(""); // NOI18N
        txtMarcaHerramienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaHerramientaActionPerformed(evt);
            }
        });

        jLabel29.setText("Stock");

        btnAgregarStockH.setText("Actualizar Stock");
        btnAgregarStockH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarStockHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HerramientasLayout = new javax.swing.GroupLayout(Herramientas);
        Herramientas.setLayout(HerramientasLayout);
        HerramientasLayout.setHorizontalGroup(
            HerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HerramientasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(HerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HerramientasLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnAgregarHerramienta))
                    .addGroup(HerramientasLayout.createSequentialGroup()
                        .addGroup(HerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreHerramienta, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(txtMarcaHerramienta)
                            .addComponent(spinnerStockHerramienta))))
                .addContainerGap(411, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HerramientasLayout.createSequentialGroup()
                .addContainerGap(271, Short.MAX_VALUE)
                .addComponent(btnBuscarHerramienta)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarStockH)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarHerramienta)
                .addGap(18, 18, 18)
                .addComponent(btnListadoHerramienta)
                .addContainerGap())
        );
        HerramientasLayout.setVerticalGroup(
            HerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HerramientasLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addGroup(HerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HerramientasLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txtMarcaHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(HerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerStockHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtNombreHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregarHerramienta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addGroup(HerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListadoHerramienta)
                    .addComponent(btnEliminarHerramienta)
                    .addComponent(btnBuscarHerramienta)
                    .addComponent(btnAgregarStockH))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Herramientas", Herramientas);

        Materiales.setBackground(new java.awt.Color(253, 202, 225));

        btnAgregarMaterial.setText("Confirmar");
        btnAgregarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMaterialActionPerformed(evt);
            }
        });

        btnBuscarMaterial.setText("Buscar");
        btnBuscarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMaterialActionPerformed(evt);
            }
        });

        btnListadoMaterial.setText("Ver Listado");
        btnListadoMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoMaterialActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("INGRESO NUEVO MATERIAL");

        jLabel21.setText("Materia Prima");

        cBMateriaPrima.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acero", "Aluminio", "Bronce", "Madera", "Chapa Galvanizada", "Chapa Negra" }));

        jLabel23.setText("Tipo");

        jLabel31.setText("Medida");

        jLabel24.setText("Stock");

        btnAgregarStockM.setText("Actualizar Stock");
        btnAgregarStockM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarStockMActionPerformed(evt);
            }
        });

        btnNuevaMatPrima.setText("Agregar Materia Prima");
        btnNuevaMatPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaMatPrimaActionPerformed(evt);
            }
        });

        btnEliminarMaterial.setText("Eliminar Material");
        btnEliminarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMaterialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MaterialesLayout = new javax.swing.GroupLayout(Materiales);
        Materiales.setLayout(MaterialesLayout);
        MaterialesLayout.setHorizontalGroup(
            MaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaterialesLayout.createSequentialGroup()
                .addGroup(MaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MaterialesLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(MaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MaterialesLayout.createSequentialGroup()
                                .addGroup(MaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(MaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cBMateriaPrima, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTipoMaterial)
                                    .addComponent(txtMedida)
                                    .addComponent(spinnerStockMaterial))
                                .addGap(18, 18, 18)
                                .addComponent(btnNuevaMatPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(MaterialesLayout.createSequentialGroup()
                        .addGroup(MaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MaterialesLayout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(btnAgregarMaterial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MaterialesLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscarMaterial)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarStockM)
                                .addGap(18, 18, 18)))
                        .addComponent(btnEliminarMaterial)))
                .addGap(18, 18, 18)
                .addComponent(btnListadoMaterial)
                .addContainerGap())
        );
        MaterialesLayout.setVerticalGroup(
            MaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MaterialesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(MaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevaMatPrima))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(MaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(spinnerStockMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregarMaterial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addGroup(MaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListadoMaterial)
                    .addComponent(btnAgregarStockM)
                    .addComponent(btnEliminarMaterial)
                    .addComponent(btnBuscarMaterial))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Materiales", Materiales);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListadoRetiroHerramientasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoRetiroHerramientasActionPerformed
        JFrame vistaList = new Vista.vistaListado();
        vistaList.setVisible(true);
        vistaListado.CBListado.setSelectedIndex(3);
        
    }//GEN-LAST:event_btnListadoRetiroHerramientasActionPerformed

    private void txtResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResponsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResponsableActionPerformed

    private void btnAgregarRetiroHerramientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRetiroHerramientaActionPerformed
        
        if (txtResponsable.getText().isEmpty() || txtIDApellidoDocente.getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "Hay campos vacíos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int idHerr = Integer.parseInt(cBIDHerramienta.getSelectedItem().toString());
            int cantidad = (int)spinnerStockRH.getValue();
            if (HerramientaControlador.chequearStockHerramienta(idHerr, cantidad) != null){
            RetiroHerramControlador.agregarRetiroHerramienta();
            }
        }      
    }//GEN-LAST:event_btnAgregarRetiroHerramientaActionPerformed

    private void btnDevolucionHerramientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucionHerramientaActionPerformed
        System.out.println("Devolver Herramienta");
    }//GEN-LAST:event_btnDevolucionHerramientaActionPerformed

    private void txtFechaRetiroHerramientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaRetiroHerramientaActionPerformed
      
    }//GEN-LAST:event_txtFechaRetiroHerramientaActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnAgregarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDocenteActionPerformed
        if (txtApellido.getText().isEmpty() || txtNombre.getText().isEmpty() || txtTelefono.getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "Hay campos vacíos", "Error", JOptionPane.ERROR_MESSAGE);
       } else {
            DocenteControlador.agregarDocente();
        }    
    }//GEN-LAST:event_btnAgregarDocenteActionPerformed

    private void btnListadoDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoDocenteActionPerformed
        JFrame vistaList = new Vista.vistaListado();
        vistaList.setVisible(true);
        vistaListado.CBListado.setSelectedIndex(0);
    }//GEN-LAST:event_btnListadoDocenteActionPerformed

    private void btnEliminarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDocenteActionPerformed
        int idABorrar = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el Id del docente a eliminar", "Eliminar Docente", JOptionPane.DEFAULT_OPTION));
        if(idABorrar >= 0) {
            DocenteControlador.borrarDocente(idABorrar);
            } else {
            JOptionPane.showMessageDialog(null, "EL ID ingresado no es válido");
        }   
    }//GEN-LAST:event_btnEliminarDocenteActionPerformed

    private void btnEditarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDocenteActionPerformed
        JFrame vistaEdit = new Vista.vistaEditar();
        vistaEdit.setVisible(true);
        
    }//GEN-LAST:event_btnEditarDocenteActionPerformed

    private void btnAgregarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMaterialActionPerformed
        if (txtTipoMaterial.getText().isEmpty() || txtMedida.getText().isEmpty() || (int) spinnerStockMaterial.getValue() == 0){
             JOptionPane.showMessageDialog(null, "Hay campos vacíos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            MaterialControlador.agregarMaterial();
        }
    }//GEN-LAST:event_btnAgregarMaterialActionPerformed

    private void btnListadoMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoMaterialActionPerformed
        JFrame vistaList = new Vista.vistaListado();
        vistaList.setVisible(true);
        vistaListado.CBListado.setSelectedIndex(2);       
    }//GEN-LAST:event_btnListadoMaterialActionPerformed

    private void txtNombreHerramientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreHerramientaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreHerramientaActionPerformed

    private void txtMarcaHerramientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaHerramientaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaHerramientaActionPerformed

    private void btnAgregarHerramientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarHerramientaActionPerformed
        if (txtNombreHerramienta.getText().isEmpty() || txtMarcaHerramienta.getText().isEmpty() || (int)spinnerStockHerramienta.getValue() == 0){
             JOptionPane.showMessageDialog(null, "Hay campos vacíos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            HerramientaControlador.agregarHerramienta();
        }
    }//GEN-LAST:event_btnAgregarHerramientaActionPerformed

    private void btnListadoHerramientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoHerramientaActionPerformed
        JFrame vistaList = new Vista.vistaListado();
        vistaList.setVisible(true);
        vistaListado.CBListado.setSelectedIndex(1);
    }//GEN-LAST:event_btnListadoHerramientaActionPerformed

    private void btnEliminarHerramientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarHerramientaActionPerformed
        int idABorrar = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el Id de la herramienta a eliminar", "Eliminar Herramienta", JOptionPane.DEFAULT_OPTION));
        if(idABorrar >= 0) {
            HerramientaControlador.borrarHerramienta(idABorrar);
            } else {
            JOptionPane.showMessageDialog(null, "EL ID ingresado no es válido");
        }
    }//GEN-LAST:event_btnEliminarHerramientaActionPerformed

    private void txtFechaRetiroMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaRetiroMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaRetiroMaterialActionPerformed

    private void txtResponsable2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResponsable2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResponsable2ActionPerformed

    private void btnListadoRetiroMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoRetiroMaterialActionPerformed
        JFrame vistaList = new Vista.vistaListado();
        vistaList.setVisible(true);
        vistaListado.CBListado.setSelectedIndex(4);
    }//GEN-LAST:event_btnListadoRetiroMaterialActionPerformed

    private void btnAgregarRetiroMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRetiroMaterialActionPerformed
        if (txtResponsable2.getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "Hay campos vacíos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int idHerr = Integer.parseInt(cBIDHerramienta.getSelectedItem().toString());
            int cantidad = (int)spinnerStockRH.getValue();
            if (MaterialControlador.chequearStockMaterial(idHerr, cantidad) != null){
            RetiroMaterialControlador.agregarRetiroMaterial();
            }
        }
    }//GEN-LAST:event_btnAgregarRetiroMaterialActionPerformed

    private void btnBuscarRetiroHerramientasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRetiroHerramientasActionPerformed
        JFrame vistaBusc = new Vista.vistaBuscar();
        vistaBusc.setVisible(true);
        Vista.vistaBuscar.CBBuscar.setSelectedIndex(3);
        Vista.vistaBuscar.cBBuscarPor.addItem("ID");
    }//GEN-LAST:event_btnBuscarRetiroHerramientasActionPerformed

    private void btnBuscarRetiroMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRetiroMaterialActionPerformed
        JFrame vistaBusc = new Vista.vistaBuscar();
        vistaBusc.setVisible(true);
        Vista.vistaBuscar.CBBuscar.setSelectedIndex(4);
        Vista.vistaBuscar.cBBuscarPor.addItem("ID");        
    }//GEN-LAST:event_btnBuscarRetiroMaterialActionPerformed

    private void btnBuscarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDocenteActionPerformed
        JFrame vistaBusc = new Vista.vistaBuscar();
        vistaBusc.setVisible(true);
        Vista.vistaBuscar.CBBuscar.setSelectedIndex(0);
        Vista.vistaBuscar.cBBuscarPor.addItem("ID");
        Vista.vistaBuscar.cBBuscarPor.addItem("Apellido");
        Vista.vistaBuscar.cBBuscarPor.addItem("Cargo");
    }//GEN-LAST:event_btnBuscarDocenteActionPerformed

    private void btnBuscarHerramientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHerramientaActionPerformed
        JFrame vistaBusc = new Vista.vistaBuscar();
        vistaBusc.setVisible(true);
        Vista.vistaBuscar.CBBuscar.setSelectedIndex(1);
        Vista.vistaBuscar.cBBuscarPor.addItem("ID");
        Vista.vistaBuscar.cBBuscarPor.addItem("Marca");
    }//GEN-LAST:event_btnBuscarHerramientaActionPerformed

    private void btnBuscarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMaterialActionPerformed
        JFrame vistaBusc = new Vista.vistaBuscar();
        vistaBusc.setVisible(true);
        Vista.vistaBuscar.CBBuscar.setSelectedIndex(2);
        Vista.vistaBuscar.cBBuscarPor.addItem("ID");
        Vista.vistaBuscar.cBBuscarPor.addItem("Materia Prima");        
    }//GEN-LAST:event_btnBuscarMaterialActionPerformed

    private void btnAgregarStockHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarStockHActionPerformed
        int idH = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el Id de herramienta para agregar stock", 
                                                                "Actualizar Stock", JOptionPane.DEFAULT_OPTION));
                
        if(idH >= 0) {
            HerramientaControlador.agregarStockHerramienta(idH);
        } else {
            JOptionPane.showMessageDialog(null, "EL ID ingresado no es válido");
        }
    }//GEN-LAST:event_btnAgregarStockHActionPerformed

    private void btnAgregarStockMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarStockMActionPerformed
        int idH = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el Id del material para agregar stock", 
                                                                "Actualizar Stock", JOptionPane.DEFAULT_OPTION));
                
        if(idH >= 0) {
            MaterialControlador.agregarStockMaterial(idH);
        } else {
            JOptionPane.showMessageDialog(null, "EL ID ingresado no es válido");
        }
    }//GEN-LAST:event_btnAgregarStockMActionPerformed

    private void btnNuevoCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoCargoActionPerformed
        String nuevoCargo = JOptionPane.showInputDialog(null, "Ingrese el nuevo cargo", "Crear nuevo cargo", JOptionPane.DEFAULT_OPTION);
        
        if (nuevoCargo.isEmpty()){
            JOptionPane.showMessageDialog(null, "No se ingresó ningún texto" ,"Campo vacío", JOptionPane.ERROR_MESSAGE);
        } else {
            cBCargoDocente.addItem(nuevoCargo);
            JOptionPane.showMessageDialog(null, "Nuevo cargo creado: " + nuevoCargo ,"Cargo creado", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnNuevoCargoActionPerformed

    private void cBCargoDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBCargoDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBCargoDocenteActionPerformed

    private void btnNuevaMatPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaMatPrimaActionPerformed
        String item = JOptionPane.showInputDialog(null, "Ingrese nueva materia prima", "Nueva Materia Prima", JOptionPane.DEFAULT_OPTION);
        cBMateriaPrima.addItem(item);
    }//GEN-LAST:event_btnNuevaMatPrimaActionPerformed

    private void btnEliminarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMaterialActionPerformed
        int idABorrar = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el Id del material a eliminar", "Eliminar Material", JOptionPane.DEFAULT_OPTION));
        if(idABorrar >= 0) {
            MaterialControlador.borrarMaterial(idABorrar);
            } else {
            JOptionPane.showMessageDialog(null, "EL ID ingresado no es válido");
        }
    }//GEN-LAST:event_btnEliminarMaterialActionPerformed

    private void txtIDApellidoDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDApellidoDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDApellidoDocenteActionPerformed

    private void txtIDNombreHerramientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDNombreHerramientaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDNombreHerramientaActionPerformed

    private void btnCargarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarDocenteActionPerformed
        DocenteControlador.cargarDocenteH();
    }//GEN-LAST:event_btnCargarDocenteActionPerformed

    private void btnCargarHerramientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarHerramientaActionPerformed
        HerramientaControlador.cargarHerramienta();
    }//GEN-LAST:event_btnCargarHerramientaActionPerformed

    private void txtIDApellidoDocenteMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDApellidoDocenteMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDApellidoDocenteMActionPerformed

    private void txtIDMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDMateriaPrimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDMateriaPrimaActionPerformed

    private void btnCargarDocente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarDocente1ActionPerformed
        DocenteControlador.cargarDocenteM();
    }//GEN-LAST:event_btnCargarDocente1ActionPerformed

    private void btnCargarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarMaterialActionPerformed
        MaterialControlador.cargarMaterial();
    }//GEN-LAST:event_btnCargarMaterialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Docentes;
    private javax.swing.JPanel Herramientas;
    private javax.swing.JPanel Materiales;
    private javax.swing.JPanel RetiroHerramienta;
    private javax.swing.JPanel RetiroMaterial;
    private javax.swing.JButton btnAgregarDocente;
    private javax.swing.JButton btnAgregarHerramienta;
    private javax.swing.JButton btnAgregarMaterial;
    private javax.swing.JButton btnAgregarRetiroHerramienta;
    private javax.swing.JButton btnAgregarRetiroMaterial;
    private javax.swing.JButton btnAgregarStockH;
    private javax.swing.JButton btnAgregarStockM;
    private javax.swing.JButton btnBuscarDocente;
    private javax.swing.JButton btnBuscarHerramienta;
    private javax.swing.JButton btnBuscarMaterial;
    private javax.swing.JButton btnBuscarRetiroHerramientas;
    private javax.swing.JButton btnBuscarRetiroMaterial;
    private javax.swing.JButton btnCargarDocente;
    private javax.swing.JButton btnCargarDocente1;
    private javax.swing.JButton btnCargarHerramienta;
    private javax.swing.JButton btnCargarMaterial;
    private javax.swing.JButton btnDevolucionHerramienta;
    private javax.swing.JButton btnEditarDocente;
    private javax.swing.JButton btnEliminarDocente;
    private javax.swing.JButton btnEliminarHerramienta;
    private javax.swing.JButton btnEliminarMaterial;
    private javax.swing.JButton btnListadoDocente;
    private javax.swing.JButton btnListadoHerramienta;
    private javax.swing.JButton btnListadoMaterial;
    private javax.swing.JButton btnListadoRetiroHerramientas;
    private javax.swing.JButton btnListadoRetiroMaterial;
    private javax.swing.JButton btnNuevaMatPrima;
    private javax.swing.JButton btnNuevoCargo;
    public static javax.swing.JComboBox<String> cBCargoDocente;
    public static javax.swing.JComboBox<String> cBIDDocenteH;
    public static javax.swing.JComboBox<String> cBIDDocenteM;
    public static javax.swing.JComboBox<String> cBIDHerramienta;
    public static javax.swing.JComboBox<String> cBIDMaterial;
    public static javax.swing.JComboBox<String> cBMateriaPrima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JSpinner spinnerStockHerramienta;
    public static javax.swing.JSpinner spinnerStockMaterial;
    private javax.swing.JSpinner spinnerStockRH;
    private javax.swing.JSpinner spinnerStockRM;
    public static javax.swing.JTextField txtApellido;
    public static javax.swing.JTextField txtFechaRetiroHerramienta;
    public static javax.swing.JTextField txtFechaRetiroMaterial;
    public static javax.swing.JTextField txtIDApellidoDocente;
    public static javax.swing.JTextField txtIDApellidoDocenteM;
    public static javax.swing.JTextField txtIDMarcaHerramienta;
    public static javax.swing.JTextField txtIDMateriaPrima;
    public static javax.swing.JTextField txtIDMedidaMaterial;
    public static javax.swing.JTextField txtIDNombreDocente;
    public static javax.swing.JTextField txtIDNombreDocenteM;
    public static javax.swing.JTextField txtIDNombreHerramienta;
    public static javax.swing.JTextField txtIDTipoMaterial;
    public static javax.swing.JTextField txtMarcaHerramienta;
    public static javax.swing.JTextField txtMedida;
    public static javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtNombreHerramienta;
    public static javax.swing.JTextField txtResponsable;
    private javax.swing.JTextField txtResponsable2;
    public static javax.swing.JTextField txtTelefono;
    public static javax.swing.JTextField txtTipoMaterial;
    // End of variables declaration//GEN-END:variables

    public String FechaParaM(){
        
        Date fec = new Date();
        SimpleDateFormat Hoy =  new SimpleDateFormat("dd/MM/yyyy");
        
        return Hoy.format(fec);
        }
    


}
