/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIsta;

/**
 *
 * @author Usuario
 */
public class vistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form vistaPrincipal
     */
    public vistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnAgregarMaterial = new javax.swing.JButton();
        btnEditarMaterial = new javax.swing.JButton();
        btnEliminarMaterial = new javax.swing.JButton();
        btnListaMaterial = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnAgregarHerramienta = new javax.swing.JButton();
        btnEditarHerramienta = new javax.swing.JButton();
        btnEliminarHerramienta = new javax.swing.JButton();
        btnListaHerramienta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAgregarDoc = new javax.swing.JButton();
        btnEditarDoc = new javax.swing.JButton();
        btnEliminarDoc = new javax.swing.JButton();
        btnListaDoc = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnCrearOrden = new javax.swing.JButton();
        btnEditarOrden = new javax.swing.JButton();
        btnEliminarOrden = new javax.swing.JButton();
        btnListaOrden = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Depósito Taller ");
        setBackground(new java.awt.Color(102, 102, 102));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(location());
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(680, 280));
        setResizable(false);

        jPanel5.setForeground(new java.awt.Color(102, 102, 102));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Materiales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.setAlignmentX(0.8F);
        jPanel3.setAlignmentY(0.8F);
        jPanel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(130, 200));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        btnAgregarMaterial.setText("Agregar");
        btnAgregarMaterial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMaterialActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgregarMaterial);

        btnEditarMaterial.setText("Editar");
        btnEditarMaterial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(btnEditarMaterial);

        btnEliminarMaterial.setText("Eliminar");
        btnEliminarMaterial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(btnEliminarMaterial);

        btnListaMaterial.setText("Listado");
        btnListaMaterial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(btnListaMaterial);

        jPanel5.add(jPanel3);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Herramientas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setToolTipText("");
        jPanel1.setAlignmentX(0.8F);
        jPanel1.setAlignmentY(0.8F);
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(130, 200));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        btnAgregarHerramienta.setText("Agregar");
        btnAgregarHerramienta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarHerramienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarHerramientaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarHerramienta);

        btnEditarHerramienta.setText("Editar");
        btnEditarHerramienta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(btnEditarHerramienta);

        btnEliminarHerramienta.setText("Eliminar");
        btnEliminarHerramienta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(btnEliminarHerramienta);

        btnListaHerramienta.setText("Listado");
        btnListaHerramienta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(btnListaHerramienta);

        jPanel5.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Docentes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setToolTipText("");
        jPanel2.setAlignmentX(1.5F);
        jPanel2.setAlignmentY(1.5F);
        jPanel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(130, 200));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        btnAgregarDoc.setText("Agregar");
        btnAgregarDoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDocActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarDoc);

        btnEditarDoc.setText("Editar");
        btnEditarDoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(btnEditarDoc);

        btnEliminarDoc.setText("Eliminar");
        btnEliminarDoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(btnEliminarDoc);

        btnListaDoc.setText("Listado");
        btnListaDoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(btnListaDoc);

        jPanel5.add(jPanel2);
        jPanel2.getAccessibleContext().setAccessibleName("");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 14), new java.awt.Color(153, 153, 153)), "Órdenes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel4.setAlignmentX(0.8F);
        jPanel4.setAlignmentY(0.8F);
        jPanel4.setFocusCycleRoot(true);
        jPanel4.setPreferredSize(new java.awt.Dimension(130, 200));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        btnCrearOrden.setText("Crear");
        btnCrearOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearOrdenActionPerformed(evt);
            }
        });
        jPanel4.add(btnCrearOrden);

        btnEditarOrden.setText("Editar");
        jPanel4.add(btnEditarOrden);

        btnEliminarOrden.setText("Eliminar");
        jPanel4.add(btnEliminarOrden);

        btnListaOrden.setText("Listado");
        jPanel4.add(btnListaOrden);

        jPanel5.add(jPanel4);
        jPanel4.getAccessibleContext().setAccessibleName("");

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Cerrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Materiales");

        jMenuItem2.setText("Agregar material");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Editar material");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Eliminar material");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Listado de materiales");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Herramientas");

        jMenuItem6.setText("Nueva herramienta");
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Editar herramientas");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Eliminar herramienta");
        jMenu3.add(jMenuItem8);

        jMenuItem9.setText("Listado completo ");
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Docentes");

        jMenuItem10.setText("Agregar docente");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuItem11.setText("Editar docente");
        jMenu4.add(jMenuItem11);

        jMenuItem12.setText("Eliminar docente");
        jMenu4.add(jMenuItem12);

        jMenuItem13.setText("Listado docentes");
        jMenu4.add(jMenuItem13);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Ordenes");

        jMenuItem14.setText("Crear orden");
        jMenu6.add(jMenuItem14);

        jMenuItem15.setText("Editar orden");
        jMenu6.add(jMenuItem15);

        jMenuItem16.setText("Eliminar orden");
        jMenu6.add(jMenuItem16);

        jMenuItem17.setText("Listado ordenes");
        jMenu6.add(jMenuItem17);

        jMenuBar1.add(jMenu6);

        jMenu5.setText("Acerca de");

        jMenuItem18.setText("Acerca de");
        jMenu5.add(jMenuItem18);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void btnAgregarHerramientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarHerramientaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarHerramientaActionPerformed

    private void btnAgregarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarDocActionPerformed

    private void btnCrearOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearOrdenActionPerformed

    private void btnAgregarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMaterialActionPerformed
        System.out.println("Aprete el boton de agregar material");        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarMaterialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarDoc;
    private javax.swing.JButton btnAgregarHerramienta;
    private javax.swing.JButton btnAgregarMaterial;
    private javax.swing.JButton btnCrearOrden;
    private javax.swing.JButton btnEditarDoc;
    private javax.swing.JButton btnEditarHerramienta;
    private javax.swing.JButton btnEditarMaterial;
    private javax.swing.JButton btnEditarOrden;
    private javax.swing.JButton btnEliminarDoc;
    private javax.swing.JButton btnEliminarHerramienta;
    private javax.swing.JButton btnEliminarMaterial;
    private javax.swing.JButton btnEliminarOrden;
    private javax.swing.JButton btnListaDoc;
    private javax.swing.JButton btnListaHerramienta;
    private javax.swing.JButton btnListaMaterial;
    private javax.swing.JButton btnListaOrden;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
